name: check_code_quality
on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le code depuis le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Remplacez par la version de Python que vous utilisez

      # Installer les dépendances
      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      # Lancer Black pour vérifier le formatage
      - name: Run Black
        run: black --check --verbose .